name: ail-411-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - jupyter
  - scikit-learn
  - torch
  - torchvision
  - torchaudio
  - tensorflow
  # - tensorflow-macos for Mac M1/M2 (run this before : conda install -c apple tensorflow-deps)
  # - tensorflow-metal for Mac M1/M2
  - tensorflow-datasets
  - tensorflow_addons
  - seaborn
  - opencv-python
  - scikit-image
  